# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela_client
from vela_client.models.v1_list_target_response import V1ListTargetResponse  # noqa: E501
from vela_client.rest import ApiException


class TestV1ListTargetResponse(unittest.TestCase):
    """V1ListTargetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ListTargetResponse(self):
        """Test V1ListTargetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_list_target_response.V1ListTargetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
