# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela_client
from vela_client.models.model_application_trait import ModelApplicationTrait  # noqa: E501
from vela_client.rest import ApiException


class TestModelApplicationTrait(unittest.TestCase):
    """ModelApplicationTrait unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelApplicationTrait(self):
        """Test ModelApplicationTrait"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model_application_trait.ModelApplicationTrait()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
