# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela_client
from vela_client.models.v1_chart_version_list_response import V1ChartVersionListResponse  # noqa: E501
from vela_client.rest import ApiException


class TestV1ChartVersionListResponse(unittest.TestCase):
    """V1ChartVersionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ChartVersionListResponse(self):
        """Test V1ChartVersionListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_chart_version_list_response.V1ChartVersionListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
