# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela_client
from vela_client.models.v1_config import V1Config  # noqa: E501
from vela_client.rest import ApiException


class TestV1Config(unittest.TestCase):
    """V1Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1Config(self):
        """Test V1Config"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_config.V1Config()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
