# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela_client
from vela_client.models.v1_create_project_request import V1CreateProjectRequest  # noqa: E501
from vela_client.rest import ApiException


class TestV1CreateProjectRequest(unittest.TestCase):
    """V1CreateProjectRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CreateProjectRequest(self):
        """Test V1CreateProjectRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_create_project_request.V1CreateProjectRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
