# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela_client
from vela_client.models.v1_cloud_shell_prepare_response import V1CloudShellPrepareResponse  # noqa: E501
from vela_client.rest import ApiException


class TestV1CloudShellPrepareResponse(unittest.TestCase):
    """V1CloudShellPrepareResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CloudShellPrepareResponse(self):
        """Test V1CloudShellPrepareResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_cloud_shell_prepare_response.V1CloudShellPrepareResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
