# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela_client
from vela_client.models.v1_pipeline_meta import V1PipelineMeta  # noqa: E501
from vela_client.rest import ApiException


class TestV1PipelineMeta(unittest.TestCase):
    """V1PipelineMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PipelineMeta(self):
        """Test V1PipelineMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_pipeline_meta.V1PipelineMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
