# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vela_client
from vela_client.models.v1alpha1_step_status import V1alpha1StepStatus  # noqa: E501
from vela_client.rest import ApiException


class TestV1alpha1StepStatus(unittest.TestCase):
    """V1alpha1StepStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1StepStatus(self):
        """Test V1alpha1StepStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1alpha1_step_status.V1alpha1StepStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
