# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AddonSystemRequirements(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'kubernetes': 'str',
        'vela': 'str'
    }

    attribute_map = {
        'kubernetes': 'kubernetes',
        'vela': 'vela'
    }

    def __init__(self, kubernetes=None, vela=None):  # noqa: E501
        """AddonSystemRequirements - a model defined in Swagger"""  # noqa: E501
        self._kubernetes = None
        self._vela = None
        self.discriminator = None
        if kubernetes is not None:
            self.kubernetes = kubernetes
        if vela is not None:
            self.vela = vela

    @property
    def kubernetes(self):
        """Gets the kubernetes of this AddonSystemRequirements.  # noqa: E501


        :return: The kubernetes of this AddonSystemRequirements.  # noqa: E501
        :rtype: str
        """
        return self._kubernetes

    @kubernetes.setter
    def kubernetes(self, kubernetes):
        """Sets the kubernetes of this AddonSystemRequirements.


        :param kubernetes: The kubernetes of this AddonSystemRequirements.  # noqa: E501
        :type: str
        """

        self._kubernetes = kubernetes

    @property
    def vela(self):
        """Gets the vela of this AddonSystemRequirements.  # noqa: E501


        :return: The vela of this AddonSystemRequirements.  # noqa: E501
        :rtype: str
        """
        return self._vela

    @vela.setter
    def vela(self, vela):
        """Sets the vela of this AddonSystemRequirements.


        :param vela: The vela of this AddonSystemRequirements.  # noqa: E501
        :type: str
        """

        self._vela = vela

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddonSystemRequirements, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddonSystemRequirements):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
