# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigDistribution(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application': 'TypesNamespacedName',
        'configs': 'list[ConfigNamespacedName]',
        'created_time': 'datetime',
        'name': 'str',
        'namespace': 'str',
        'status': 'CommonAppStatus',
        'targets': 'list[ConfigClusterTarget]'
    }

    attribute_map = {
        'application': 'application',
        'configs': 'configs',
        'created_time': 'createdTime',
        'name': 'name',
        'namespace': 'namespace',
        'status': 'status',
        'targets': 'targets'
    }

    def __init__(self, application=None, configs=None, created_time=None, name=None, namespace=None, status=None, targets=None):  # noqa: E501
        """ConfigDistribution - a model defined in Swagger"""  # noqa: E501
        self._application = None
        self._configs = None
        self._created_time = None
        self._name = None
        self._namespace = None
        self._status = None
        self._targets = None
        self.discriminator = None
        self.application = application
        self.configs = configs
        self.created_time = created_time
        self.name = name
        self.namespace = namespace
        self.status = status
        self.targets = targets

    @property
    def application(self):
        """Gets the application of this ConfigDistribution.  # noqa: E501


        :return: The application of this ConfigDistribution.  # noqa: E501
        :rtype: TypesNamespacedName
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this ConfigDistribution.


        :param application: The application of this ConfigDistribution.  # noqa: E501
        :type: TypesNamespacedName
        """
        if application is None:
            raise ValueError("Invalid value for `application`, must not be `None`")  # noqa: E501

        self._application = application

    @property
    def configs(self):
        """Gets the configs of this ConfigDistribution.  # noqa: E501


        :return: The configs of this ConfigDistribution.  # noqa: E501
        :rtype: list[ConfigNamespacedName]
        """
        return self._configs

    @configs.setter
    def configs(self, configs):
        """Sets the configs of this ConfigDistribution.


        :param configs: The configs of this ConfigDistribution.  # noqa: E501
        :type: list[ConfigNamespacedName]
        """
        if configs is None:
            raise ValueError("Invalid value for `configs`, must not be `None`")  # noqa: E501

        self._configs = configs

    @property
    def created_time(self):
        """Gets the created_time of this ConfigDistribution.  # noqa: E501


        :return: The created_time of this ConfigDistribution.  # noqa: E501
        :rtype: datetime
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this ConfigDistribution.


        :param created_time: The created_time of this ConfigDistribution.  # noqa: E501
        :type: datetime
        """
        if created_time is None:
            raise ValueError("Invalid value for `created_time`, must not be `None`")  # noqa: E501

        self._created_time = created_time

    @property
    def name(self):
        """Gets the name of this ConfigDistribution.  # noqa: E501


        :return: The name of this ConfigDistribution.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConfigDistribution.


        :param name: The name of this ConfigDistribution.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this ConfigDistribution.  # noqa: E501


        :return: The namespace of this ConfigDistribution.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this ConfigDistribution.


        :param namespace: The namespace of this ConfigDistribution.  # noqa: E501
        :type: str
        """
        if namespace is None:
            raise ValueError("Invalid value for `namespace`, must not be `None`")  # noqa: E501

        self._namespace = namespace

    @property
    def status(self):
        """Gets the status of this ConfigDistribution.  # noqa: E501


        :return: The status of this ConfigDistribution.  # noqa: E501
        :rtype: CommonAppStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ConfigDistribution.


        :param status: The status of this ConfigDistribution.  # noqa: E501
        :type: CommonAppStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def targets(self):
        """Gets the targets of this ConfigDistribution.  # noqa: E501


        :return: The targets of this ConfigDistribution.  # noqa: E501
        :rtype: list[ConfigClusterTarget]
        """
        return self._targets

    @targets.setter
    def targets(self, targets):
        """Sets the targets of this ConfigDistribution.


        :param targets: The targets of this ConfigDistribution.  # noqa: E501
        :type: list[ConfigClusterTarget]
        """
        if targets is None:
            raise ValueError("Invalid value for `targets`, must not be `None`")  # noqa: E501

        self._targets = targets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigDistribution, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigDistribution):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
