# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1AppDryRunReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dry_run_type': 'str',
        'env': 'str',
        'version': 'str',
        'workflow': 'str'
    }

    attribute_map = {
        'dry_run_type': 'dryRunType',
        'env': 'env',
        'version': 'version',
        'workflow': 'workflow'
    }

    def __init__(self, dry_run_type=None, env=None, version=None, workflow=None):  # noqa: E501
        """V1AppDryRunReq - a model defined in Swagger"""  # noqa: E501
        self._dry_run_type = None
        self._env = None
        self._version = None
        self._workflow = None
        self.discriminator = None
        self.dry_run_type = dry_run_type
        self.env = env
        self.version = version
        self.workflow = workflow

    @property
    def dry_run_type(self):
        """Gets the dry_run_type of this V1AppDryRunReq.  # noqa: E501


        :return: The dry_run_type of this V1AppDryRunReq.  # noqa: E501
        :rtype: str
        """
        return self._dry_run_type

    @dry_run_type.setter
    def dry_run_type(self, dry_run_type):
        """Sets the dry_run_type of this V1AppDryRunReq.


        :param dry_run_type: The dry_run_type of this V1AppDryRunReq.  # noqa: E501
        :type: str
        """
        if dry_run_type is None:
            raise ValueError("Invalid value for `dry_run_type`, must not be `None`")  # noqa: E501

        self._dry_run_type = dry_run_type

    @property
    def env(self):
        """Gets the env of this V1AppDryRunReq.  # noqa: E501


        :return: The env of this V1AppDryRunReq.  # noqa: E501
        :rtype: str
        """
        return self._env

    @env.setter
    def env(self, env):
        """Sets the env of this V1AppDryRunReq.


        :param env: The env of this V1AppDryRunReq.  # noqa: E501
        :type: str
        """
        if env is None:
            raise ValueError("Invalid value for `env`, must not be `None`")  # noqa: E501

        self._env = env

    @property
    def version(self):
        """Gets the version of this V1AppDryRunReq.  # noqa: E501


        :return: The version of this V1AppDryRunReq.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this V1AppDryRunReq.


        :param version: The version of this V1AppDryRunReq.  # noqa: E501
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def workflow(self):
        """Gets the workflow of this V1AppDryRunReq.  # noqa: E501


        :return: The workflow of this V1AppDryRunReq.  # noqa: E501
        :rtype: str
        """
        return self._workflow

    @workflow.setter
    def workflow(self, workflow):
        """Sets the workflow of this V1AppDryRunReq.


        :param workflow: The workflow of this V1AppDryRunReq.  # noqa: E501
        :type: str
        """
        if workflow is None:
            raise ValueError("Invalid value for `workflow`, must not be `None`")  # noqa: E501

        self._workflow = workflow

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1AppDryRunReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1AppDryRunReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
