# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1AddProjectUserRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_name': 'str',
        'user_roles': 'list[str]'
    }

    attribute_map = {
        'user_name': 'userName',
        'user_roles': 'userRoles'
    }

    def __init__(self, user_name=None, user_roles=None):  # noqa: E501
        """V1AddProjectUserRequest - a model defined in Swagger"""  # noqa: E501
        self._user_name = None
        self._user_roles = None
        self.discriminator = None
        self.user_name = user_name
        self.user_roles = user_roles

    @property
    def user_name(self):
        """Gets the user_name of this V1AddProjectUserRequest.  # noqa: E501


        :return: The user_name of this V1AddProjectUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this V1AddProjectUserRequest.


        :param user_name: The user_name of this V1AddProjectUserRequest.  # noqa: E501
        :type: str
        """
        if user_name is None:
            raise ValueError("Invalid value for `user_name`, must not be `None`")  # noqa: E501

        self._user_name = user_name

    @property
    def user_roles(self):
        """Gets the user_roles of this V1AddProjectUserRequest.  # noqa: E501


        :return: The user_roles of this V1AddProjectUserRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._user_roles

    @user_roles.setter
    def user_roles(self, user_roles):
        """Sets the user_roles of this V1AddProjectUserRequest.


        :param user_roles: The user_roles of this V1AddProjectUserRequest.  # noqa: E501
        :type: list[str]
        """
        if user_roles is None:
            raise ValueError("Invalid value for `user_roles`, must not be `None`")  # noqa: E501

        self._user_roles = user_roles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1AddProjectUserRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1AddProjectUserRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
