# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1CreateApplicationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias': 'str',
        'component': 'V1CreateComponentRequest',
        'description': 'str',
        'env_binding': 'list[V1EnvBinding]',
        'icon': 'str',
        'labels': 'dict(str, str)',
        'name': 'str',
        'project': 'str'
    }

    attribute_map = {
        'alias': 'alias',
        'component': 'component',
        'description': 'description',
        'env_binding': 'envBinding',
        'icon': 'icon',
        'labels': 'labels',
        'name': 'name',
        'project': 'project'
    }

    def __init__(self, alias=None, component=None, description=None, env_binding=None, icon=None, labels=None, name=None, project=None):  # noqa: E501
        """V1CreateApplicationRequest - a model defined in Swagger"""  # noqa: E501
        self._alias = None
        self._component = None
        self._description = None
        self._env_binding = None
        self._icon = None
        self._labels = None
        self._name = None
        self._project = None
        self.discriminator = None
        if alias is not None:
            self.alias = alias
        self.component = component
        if description is not None:
            self.description = description
        if env_binding is not None:
            self.env_binding = env_binding
        self.icon = icon
        if labels is not None:
            self.labels = labels
        self.name = name
        self.project = project

    @property
    def alias(self):
        """Gets the alias of this V1CreateApplicationRequest.  # noqa: E501


        :return: The alias of this V1CreateApplicationRequest.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this V1CreateApplicationRequest.


        :param alias: The alias of this V1CreateApplicationRequest.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def component(self):
        """Gets the component of this V1CreateApplicationRequest.  # noqa: E501


        :return: The component of this V1CreateApplicationRequest.  # noqa: E501
        :rtype: V1CreateComponentRequest
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this V1CreateApplicationRequest.


        :param component: The component of this V1CreateApplicationRequest.  # noqa: E501
        :type: V1CreateComponentRequest
        """
        if component is None:
            raise ValueError("Invalid value for `component`, must not be `None`")  # noqa: E501

        self._component = component

    @property
    def description(self):
        """Gets the description of this V1CreateApplicationRequest.  # noqa: E501


        :return: The description of this V1CreateApplicationRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this V1CreateApplicationRequest.


        :param description: The description of this V1CreateApplicationRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def env_binding(self):
        """Gets the env_binding of this V1CreateApplicationRequest.  # noqa: E501


        :return: The env_binding of this V1CreateApplicationRequest.  # noqa: E501
        :rtype: list[V1EnvBinding]
        """
        return self._env_binding

    @env_binding.setter
    def env_binding(self, env_binding):
        """Sets the env_binding of this V1CreateApplicationRequest.


        :param env_binding: The env_binding of this V1CreateApplicationRequest.  # noqa: E501
        :type: list[V1EnvBinding]
        """

        self._env_binding = env_binding

    @property
    def icon(self):
        """Gets the icon of this V1CreateApplicationRequest.  # noqa: E501


        :return: The icon of this V1CreateApplicationRequest.  # noqa: E501
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """Sets the icon of this V1CreateApplicationRequest.


        :param icon: The icon of this V1CreateApplicationRequest.  # noqa: E501
        :type: str
        """
        if icon is None:
            raise ValueError("Invalid value for `icon`, must not be `None`")  # noqa: E501

        self._icon = icon

    @property
    def labels(self):
        """Gets the labels of this V1CreateApplicationRequest.  # noqa: E501


        :return: The labels of this V1CreateApplicationRequest.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this V1CreateApplicationRequest.


        :param labels: The labels of this V1CreateApplicationRequest.  # noqa: E501
        :type: dict(str, str)
        """

        self._labels = labels

    @property
    def name(self):
        """Gets the name of this V1CreateApplicationRequest.  # noqa: E501


        :return: The name of this V1CreateApplicationRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1CreateApplicationRequest.


        :param name: The name of this V1CreateApplicationRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def project(self):
        """Gets the project of this V1CreateApplicationRequest.  # noqa: E501


        :return: The project of this V1CreateApplicationRequest.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this V1CreateApplicationRequest.


        :param project: The project of this V1CreateApplicationRequest.  # noqa: E501
        :type: str
        """
        if project is None:
            raise ValueError("Invalid value for `project`, must not be `None`")  # noqa: E501

        self._project = project

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1CreateApplicationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1CreateApplicationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
