# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1CreateProjectRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias': 'str',
        'description': 'str',
        'name': 'str',
        'namespace': 'str',
        'owner': 'str'
    }

    attribute_map = {
        'alias': 'alias',
        'description': 'description',
        'name': 'name',
        'namespace': 'namespace',
        'owner': 'owner'
    }

    def __init__(self, alias=None, description=None, name=None, namespace=None, owner=None):  # noqa: E501
        """V1CreateProjectRequest - a model defined in Swagger"""  # noqa: E501
        self._alias = None
        self._description = None
        self._name = None
        self._namespace = None
        self._owner = None
        self.discriminator = None
        if alias is not None:
            self.alias = alias
        if description is not None:
            self.description = description
        self.name = name
        if namespace is not None:
            self.namespace = namespace
        if owner is not None:
            self.owner = owner

    @property
    def alias(self):
        """Gets the alias of this V1CreateProjectRequest.  # noqa: E501


        :return: The alias of this V1CreateProjectRequest.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this V1CreateProjectRequest.


        :param alias: The alias of this V1CreateProjectRequest.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def description(self):
        """Gets the description of this V1CreateProjectRequest.  # noqa: E501


        :return: The description of this V1CreateProjectRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this V1CreateProjectRequest.


        :param description: The description of this V1CreateProjectRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this V1CreateProjectRequest.  # noqa: E501


        :return: The name of this V1CreateProjectRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1CreateProjectRequest.


        :param name: The name of this V1CreateProjectRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this V1CreateProjectRequest.  # noqa: E501


        :return: The namespace of this V1CreateProjectRequest.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this V1CreateProjectRequest.


        :param namespace: The namespace of this V1CreateProjectRequest.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def owner(self):
        """Gets the owner of this V1CreateProjectRequest.  # noqa: E501


        :return: The owner of this V1CreateProjectRequest.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this V1CreateProjectRequest.


        :param owner: The owner of this V1CreateProjectRequest.  # noqa: E501
        :type: str
        """

        self._owner = owner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1CreateProjectRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1CreateProjectRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
