# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1CreateEnvRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias': 'str',
        'allow_target_conflict': 'bool',
        'description': 'str',
        'name': 'str',
        'namespace': 'str',
        'project': 'str',
        'targets': 'list[str]'
    }

    attribute_map = {
        'alias': 'alias',
        'allow_target_conflict': 'allowTargetConflict',
        'description': 'description',
        'name': 'name',
        'namespace': 'namespace',
        'project': 'project',
        'targets': 'targets'
    }

    def __init__(self, alias=None, allow_target_conflict=None, description=None, name=None, namespace=None, project=None, targets=None):  # noqa: E501
        """V1CreateEnvRequest - a model defined in Swagger"""  # noqa: E501
        self._alias = None
        self._allow_target_conflict = None
        self._description = None
        self._name = None
        self._namespace = None
        self._project = None
        self._targets = None
        self.discriminator = None
        if alias is not None:
            self.alias = alias
        if allow_target_conflict is not None:
            self.allow_target_conflict = allow_target_conflict
        if description is not None:
            self.description = description
        self.name = name
        self.namespace = namespace
        self.project = project
        if targets is not None:
            self.targets = targets

    @property
    def alias(self):
        """Gets the alias of this V1CreateEnvRequest.  # noqa: E501


        :return: The alias of this V1CreateEnvRequest.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this V1CreateEnvRequest.


        :param alias: The alias of this V1CreateEnvRequest.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def allow_target_conflict(self):
        """Gets the allow_target_conflict of this V1CreateEnvRequest.  # noqa: E501


        :return: The allow_target_conflict of this V1CreateEnvRequest.  # noqa: E501
        :rtype: bool
        """
        return self._allow_target_conflict

    @allow_target_conflict.setter
    def allow_target_conflict(self, allow_target_conflict):
        """Sets the allow_target_conflict of this V1CreateEnvRequest.


        :param allow_target_conflict: The allow_target_conflict of this V1CreateEnvRequest.  # noqa: E501
        :type: bool
        """

        self._allow_target_conflict = allow_target_conflict

    @property
    def description(self):
        """Gets the description of this V1CreateEnvRequest.  # noqa: E501


        :return: The description of this V1CreateEnvRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this V1CreateEnvRequest.


        :param description: The description of this V1CreateEnvRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this V1CreateEnvRequest.  # noqa: E501


        :return: The name of this V1CreateEnvRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1CreateEnvRequest.


        :param name: The name of this V1CreateEnvRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this V1CreateEnvRequest.  # noqa: E501


        :return: The namespace of this V1CreateEnvRequest.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this V1CreateEnvRequest.


        :param namespace: The namespace of this V1CreateEnvRequest.  # noqa: E501
        :type: str
        """
        if namespace is None:
            raise ValueError("Invalid value for `namespace`, must not be `None`")  # noqa: E501

        self._namespace = namespace

    @property
    def project(self):
        """Gets the project of this V1CreateEnvRequest.  # noqa: E501


        :return: The project of this V1CreateEnvRequest.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this V1CreateEnvRequest.


        :param project: The project of this V1CreateEnvRequest.  # noqa: E501
        :type: str
        """
        if project is None:
            raise ValueError("Invalid value for `project`, must not be `None`")  # noqa: E501

        self._project = project

    @property
    def targets(self):
        """Gets the targets of this V1CreateEnvRequest.  # noqa: E501


        :return: The targets of this V1CreateEnvRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._targets

    @targets.setter
    def targets(self, targets):
        """Sets the targets of this V1CreateEnvRequest.


        :param targets: The targets of this V1CreateEnvRequest.  # noqa: E501
        :type: list[str]
        """

        self._targets = targets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1CreateEnvRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1CreateEnvRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
