# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1EnableAddonRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'args': 'object',
        'clusters': 'list[str]',
        'registry_name': 'str',
        'version': 'str'
    }

    attribute_map = {
        'args': 'args',
        'clusters': 'clusters',
        'registry_name': 'registryName',
        'version': 'version'
    }

    def __init__(self, args=None, clusters=None, registry_name=None, version=None):  # noqa: E501
        """V1EnableAddonRequest - a model defined in Swagger"""  # noqa: E501
        self._args = None
        self._clusters = None
        self._registry_name = None
        self._version = None
        self.discriminator = None
        if args is not None:
            self.args = args
        if clusters is not None:
            self.clusters = clusters
        if registry_name is not None:
            self.registry_name = registry_name
        if version is not None:
            self.version = version

    @property
    def args(self):
        """Gets the args of this V1EnableAddonRequest.  # noqa: E501


        :return: The args of this V1EnableAddonRequest.  # noqa: E501
        :rtype: object
        """
        return self._args

    @args.setter
    def args(self, args):
        """Sets the args of this V1EnableAddonRequest.


        :param args: The args of this V1EnableAddonRequest.  # noqa: E501
        :type: object
        """

        self._args = args

    @property
    def clusters(self):
        """Gets the clusters of this V1EnableAddonRequest.  # noqa: E501


        :return: The clusters of this V1EnableAddonRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._clusters

    @clusters.setter
    def clusters(self, clusters):
        """Sets the clusters of this V1EnableAddonRequest.


        :param clusters: The clusters of this V1EnableAddonRequest.  # noqa: E501
        :type: list[str]
        """

        self._clusters = clusters

    @property
    def registry_name(self):
        """Gets the registry_name of this V1EnableAddonRequest.  # noqa: E501


        :return: The registry_name of this V1EnableAddonRequest.  # noqa: E501
        :rtype: str
        """
        return self._registry_name

    @registry_name.setter
    def registry_name(self, registry_name):
        """Sets the registry_name of this V1EnableAddonRequest.


        :param registry_name: The registry_name of this V1EnableAddonRequest.  # noqa: E501
        :type: str
        """

        self._registry_name = registry_name

    @property
    def version(self):
        """Gets the version of this V1EnableAddonRequest.  # noqa: E501


        :return: The version of this V1EnableAddonRequest.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this V1EnableAddonRequest.


        :param version: The version of this V1EnableAddonRequest.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1EnableAddonRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1EnableAddonRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
