# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1HandleApplicationTriggerWebhookRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code_info': 'ModelCodeInfo',
        'upgrade': 'dict(str, ModelJSONStruct)'
    }

    attribute_map = {
        'code_info': 'codeInfo',
        'upgrade': 'upgrade'
    }

    def __init__(self, code_info=None, upgrade=None):  # noqa: E501
        """V1HandleApplicationTriggerWebhookRequest - a model defined in Swagger"""  # noqa: E501
        self._code_info = None
        self._upgrade = None
        self.discriminator = None
        if code_info is not None:
            self.code_info = code_info
        if upgrade is not None:
            self.upgrade = upgrade

    @property
    def code_info(self):
        """Gets the code_info of this V1HandleApplicationTriggerWebhookRequest.  # noqa: E501


        :return: The code_info of this V1HandleApplicationTriggerWebhookRequest.  # noqa: E501
        :rtype: ModelCodeInfo
        """
        return self._code_info

    @code_info.setter
    def code_info(self, code_info):
        """Sets the code_info of this V1HandleApplicationTriggerWebhookRequest.


        :param code_info: The code_info of this V1HandleApplicationTriggerWebhookRequest.  # noqa: E501
        :type: ModelCodeInfo
        """

        self._code_info = code_info

    @property
    def upgrade(self):
        """Gets the upgrade of this V1HandleApplicationTriggerWebhookRequest.  # noqa: E501


        :return: The upgrade of this V1HandleApplicationTriggerWebhookRequest.  # noqa: E501
        :rtype: dict(str, ModelJSONStruct)
        """
        return self._upgrade

    @upgrade.setter
    def upgrade(self, upgrade):
        """Sets the upgrade of this V1HandleApplicationTriggerWebhookRequest.


        :param upgrade: The upgrade of this V1HandleApplicationTriggerWebhookRequest.  # noqa: E501
        :type: dict(str, ModelJSONStruct)
        """

        self._upgrade = upgrade

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1HandleApplicationTriggerWebhookRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1HandleApplicationTriggerWebhookRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
