# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1RunPipelineRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'context_name': 'str',
        'mode': 'V1alpha1WorkflowExecuteMode'
    }

    attribute_map = {
        'context_name': 'contextName',
        'mode': 'mode'
    }

    def __init__(self, context_name=None, mode=None):  # noqa: E501
        """V1RunPipelineRequest - a model defined in Swagger"""  # noqa: E501
        self._context_name = None
        self._mode = None
        self.discriminator = None
        self.context_name = context_name
        if mode is not None:
            self.mode = mode

    @property
    def context_name(self):
        """Gets the context_name of this V1RunPipelineRequest.  # noqa: E501


        :return: The context_name of this V1RunPipelineRequest.  # noqa: E501
        :rtype: str
        """
        return self._context_name

    @context_name.setter
    def context_name(self, context_name):
        """Sets the context_name of this V1RunPipelineRequest.


        :param context_name: The context_name of this V1RunPipelineRequest.  # noqa: E501
        :type: str
        """
        if context_name is None:
            raise ValueError("Invalid value for `context_name`, must not be `None`")  # noqa: E501

        self._context_name = context_name

    @property
    def mode(self):
        """Gets the mode of this V1RunPipelineRequest.  # noqa: E501


        :return: The mode of this V1RunPipelineRequest.  # noqa: E501
        :rtype: V1alpha1WorkflowExecuteMode
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this V1RunPipelineRequest.


        :param mode: The mode of this V1RunPipelineRequest.  # noqa: E501
        :type: V1alpha1WorkflowExecuteMode
        """

        self._mode = mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1RunPipelineRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1RunPipelineRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
