# coding: utf-8

"""
    Kubevela api doc

    Kubevela api doc  # noqa: E501

    OpenAPI spec version: v1beta1
    Contact: feedback@mail.kubevela.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1UpdateUserRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias': 'str',
        'email': 'str',
        'password': 'str',
        'roles': 'list[str]'
    }

    attribute_map = {
        'alias': 'alias',
        'email': 'email',
        'password': 'password',
        'roles': 'roles'
    }

    def __init__(self, alias=None, email=None, password=None, roles=None):  # noqa: E501
        """V1UpdateUserRequest - a model defined in Swagger"""  # noqa: E501
        self._alias = None
        self._email = None
        self._password = None
        self._roles = None
        self.discriminator = None
        if alias is not None:
            self.alias = alias
        if email is not None:
            self.email = email
        if password is not None:
            self.password = password
        self.roles = roles

    @property
    def alias(self):
        """Gets the alias of this V1UpdateUserRequest.  # noqa: E501


        :return: The alias of this V1UpdateUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this V1UpdateUserRequest.


        :param alias: The alias of this V1UpdateUserRequest.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def email(self):
        """Gets the email of this V1UpdateUserRequest.  # noqa: E501


        :return: The email of this V1UpdateUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this V1UpdateUserRequest.


        :param email: The email of this V1UpdateUserRequest.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def password(self):
        """Gets the password of this V1UpdateUserRequest.  # noqa: E501


        :return: The password of this V1UpdateUserRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this V1UpdateUserRequest.


        :param password: The password of this V1UpdateUserRequest.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def roles(self):
        """Gets the roles of this V1UpdateUserRequest.  # noqa: E501


        :return: The roles of this V1UpdateUserRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this V1UpdateUserRequest.


        :param roles: The roles of this V1UpdateUserRequest.  # noqa: E501
        :type: list[str]
        """
        if roles is None:
            raise ValueError("Invalid value for `roles`, must not be `None`")  # noqa: E501

        self._roles = roles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1UpdateUserRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1UpdateUserRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
